GITHUB_API_BASE = "https://api.github.com"
GITHUB_RAW_BASE = "https://raw.githubusercontent.com"
GITHUB_REPO_OWNER = "crackedngineer"
GITHUB_REPO_NAME = "vLEM"
GITHUB_BRANCH = "master"
GITHUB_TEMPLATES_INDEX_FILE = "templates/metadata.json"
GITHUB_TEMPLATES_BASE_PATH = "templates"