name: Deploy Preview

on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - "web/**"
            - "data/labs.json"

jobs:
    deploy-preview:
        runs-on: ubuntu-latest
        name: Deploy PR Preview
        env:
            NODE_VERSION: 22

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: "./web/package-lock.json"

            - name: Install dependencies
              working-directory: ./web
              run: npm install

            - name: Build web app
              working-directory: ./web
              run: npm run build
              env:
                  NODE_ENV: development
                  VITE_APP_VERSION: ${{ github.sha }}
                  VITE_APP_ENV: "preview"
                  VITE_PR_NUMBER: ${{ github.event.pull_request.number }}

            - name: Deploy to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: vlem
                  directory: ./web
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
              timeout-minutes: 2
