# Production Deployment Workflow
name: Deploy to Production

on:
    push:
        branches:
            - main
        paths:
            - "web/**"
            - "data/labs.json"
    workflow_dispatch:

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        name: Deploy to Netlify (Production)
        env:
            NODE_VERSION: 22

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: "./web/package-lock.json"

            - name: Install dependencies
              working-directory: ./web
              run: npm ci

            - name: Build web app
              working-directory: ./web
              run: npm run build
              env:
                  NODE_ENV: production
                  VITE_APP_VERSION: ${{ github.sha }}
                  VITE_APP_ENV: "production"

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v2
              with:
                  publish-dir: "./web/dist"
                  production-deploy: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: "Production deployment from ${{ github.event_name == 'workflow_dispatch' && 'manual trigger' || 'main branch push' }}"
                  enable-commit-comment: true
                  enable-commit-status: true
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 2
